### PR TITLE
Add target libraries/executables to executable's RPATH

### PR DESCRIPTION
**Pull request by billysuh7**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

xref: https://github.com/conda-forge/cuda-feedstock/issues/10

Only libnvvp/nvvp binary executable needs patching here.

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Comment by jakirkham** [comment]
In the test phase [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1070881&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=2074 ), this had a clobbering warning

```
ERROR:conda.stderr:
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::cuda-nvprof-12.6.80-hbd13f7d_0, local/linux-64::cuda-nvvp-12.6.80-hbd13f7d_1
  path: 'LICENSE'



done
Executing transaction: ...working... ERROR:conda.stderr:
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /home/conda/feedstock_root/build_artifacts/pkg_cache/cuda-nvvp-12.6.80-hbd13f7d_1/LICENSE
  target path: /home/conda/feedstock_root/build_artifacts/cuda-nvvp_1730696031572/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/LICENSE



done
```

This may be nothing as it is talking about the license files clobbering, which doesn't make a lot of sense. So will try restarting. If we still see it, we may want to take a closer look

**Comment by jakirkham** [comment]
@conda-forge-admin , please restart CI

**Comment by jakirkham** [comment]
For some reason CI couldn't checkout the PR. Restarting again

@conda-forge-admin , please restart CI

**Comment by jakirkham** [comment]
Going to try doing this manually

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
It seems CI is just misbehaving. To fix CI, we may need to try...

1. Pushing additional commits to this PR
2. Closing this PR and opening a new one

**Comment by billysuh7** [comment]
> In the test phase [on CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1070881&view=logs&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc&t=9eb77fd2-8ddd-5444-8fc0-71cb28dcb736&l=2074), this had a clobbering warning
> 
> ```
> ERROR:conda.stderr:
> ClobberWarning: This transaction has incompatible packages due to a shared path.
>   packages: conda-forge/linux-64::cuda-nvprof-12.6.80-hbd13f7d_0, local/linux-64::cuda-nvvp-12.6.80-hbd13f7d_1
>   path: 'LICENSE'
> 
> 
> 
> done
> Executing transaction: ...working... ERROR:conda.stderr:
> ClobberWarning: Conda was asked to clobber an existing path.
>   source path: /home/conda/feedstock_root/build_artifacts/pkg_cache/cuda-nvvp-12.6.80-hbd13f7d_1/LICENSE
>   target path: /home/conda/feedstock_root/build_artifacts/cuda-nvvp_1730696031572/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/LICENSE
> 
> 
> 
> done
> ```
> 
> This may be nothing as it is talking about the license files clobbering, which doesn't make a lot of sense. So will try restarting. If we still see it, we may want to take a closer look

I believe above is a legit warning but innocuous ? Both `cuda-nvpp` and `cuda-nvprof` contain LICENSE file at the root of their package ($PREFIX). I see that some feedstocks (like these) do not explicitly define `files:` section in which case all files from source tar seem to get packaged.

As a test I installed `cuda-nvvp` (the GA version of `12.6.80`) and I see:

```
(test2) bsuh@cia-dev-bsuh-01:~/miniforge3/envs/test2$ conda list
# packages in environment at /home/bsuh/miniforge3/envs/test2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
cuda-cupti                12.6.80              hbd13f7d_0    conda-forge
cuda-nvdisasm             12.6.77              hbd13f7d_0    conda-forge
cuda-nvprof               12.6.80              hbd13f7d_0    conda-forge
cuda-nvvp                 12.6.80              hbd13f7d_0    conda-forge
cuda-version              12.6                 h7480c83_3    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
(test2) bsuh@cia-dev-bsuh-01:~/miniforge3/envs/test2$ ll
total 96
drwxrwxr-x  8 bsuh bsuh  4096 Nov  4 00:43 ./
drwxrwxr-x 20 bsuh bsuh  4096 Nov  5 14:42 ../
drwxrwxr-x  2 bsuh bsuh  4096 Nov  4 00:43 bin/
drwxrwxr-x  2 bsuh bsuh  4096 Nov  4 00:43 conda-meta/
drwxrwxr-x  3 bsuh bsuh  4096 Nov  4 00:43 lib/
drwxrwxr-x  7 bsuh bsuh  4096 Nov  4 00:43 libnvvp/
-rw-rw-r--  2 bsuh bsuh 63021 Oct  1 20:51 LICENSE
drwxrwxr-x  4 bsuh bsuh  4096 Nov  4 00:43 share/
drwxrwxr-x  3 bsuh bsuh  4096 Nov  4 00:43 targets/
(test2) bsuh@cia-dev-bsuh-01:~/miniforge3/envs/test2$ conda package -w LICENSE
LICENSE                                             conda-forge/linux-64::cuda-nvvp-12.6.80-hbd13f7d_0
LICENSE                                             conda-forge/linux-64::cuda-nvprof-12.6.80-hbd13f7d_0
```

**Comment by jakirkham** [comment]
Thanks Billy! 🙏

As discussed yesterday, the clobbering warning is a real issue. However it is tangential to the issue we are solving here.

To follow up on clobbering, have filed upstream issue: https://github.com/conda-forge/cuda-feedstock/issues/52

**Comment by jakirkham** [comment]
Also noticed there was a second PR opened with these changes: https://github.com/conda-forge/cuda-nvvp-feedstock/pull/15

Did we want to stick with this PR or is there something else needed in that PR?

**Comment by billysuh7** [comment]
> Also noticed there was a second PR opened with these changes: #15
> 
> Did we want to stick with this PR or is there something else needed in that PR?

I just closed #15 :) I had opened it because this PR was broken but now it seems working now.

**Comment by jakirkham** [comment]
Ah right the CI issues. Thanks Billy! 🙏

Ok let's get this in then

**Pull request merged**
